---
development:
  cloud_name: dush6wf6z
  api_key: '481537939787419'
  api_secret: 9jZeZPHh2N2pLPRyKjzKsRTDgrc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dush6wf6z
  api_key: '481537939787419'
  api_secret: 9jZeZPHh2N2pLPRyKjzKsRTDgrc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dush6wf6z
  api_key: '481537939787419'
  api_secret: 9jZeZPHh2N2pLPRyKjzKsRTDgrc
  enhance_image_tag: true
  static_image_support: false
